### ISSUE TITLE
App registration fails, not the beta program

### ISSUE THREAD

**Issue by DelofJ** [BedrockLauncher/BedrockLauncher#242]
Here https://github.com/BedrockLauncher/BedrockLauncher/issues/240 I didn't talk about the beta program
It is the suite of this issue https://github.com/BedrockLauncher/BedrockLauncher/issues/39
I have the beta installed on my computer, it's not an issue that I can't download the beta from MS servers since it's discontined
The appx itself can register this version of Minecraft but the launcher can't
> I don't know if it's the same problem but it crashes when I want to load a beta version of Minecraft which is no longer available for download from the MS servers but which I still have on my computer

(said here https://github.com/BedrockLauncher/BedrockLauncher/issues/39#issuecomment-1170611413)
This is a problem because people who archived the betas of Minecraft can no longer play them through the launcher even if they have them

**Comment by Rayth** [comment]
I closed it because the developer has said it won't be worked on. We have full preview support now. Old betas are useless anyway, as the release version after that beta contains all those beta features.

![image](https://user-images.githubusercontent.com/4260473/177202295-4a8404cc-c4ab-4c84-83b2-894b4f0ce373.png)

This translation also means we'd have to change the launcher entirely. It defies the fundamental principle the launcher is built on.

If you encounter this issue with a preview or up to date release, we will re-look at the situation but you're only encountering it for beta versions from before preview.

**Comment by DelofJ** [comment]
Nevermind
