### ISSUE TITLE
You require a program that I have installed, yet this launcher says I don't.

### ISSUE THREAD

**Issue by MagmaBro123** [BedrockLauncher/BedrockLauncher#279]
Title. Windows 10.

![image](https://user-images.githubusercontent.com/51277766/186564302-b2a767c5-96ec-41c2-8245-d4f66d5aae89.png)

![image](https://user-images.githubusercontent.com/51277766/186564427-ae764879-cd5d-4b02-9a97-fa1d24d22459.png)

**Comment by tresabhi** [comment]
Try following instructions here: [#195 (comment)](https://github.com/BedrockLauncher/BedrockLauncher/issues/195#issuecomment-1103371313)

**Comment by Rayth** [comment]
If you actually read the popup, it says you are missing frameworks for .NET not that you are missing Microsoft.Net runtime.

Don't follow the above instructions because they're actually out-dated now as the latest pre-release should remove all requirement of needing ASP.Net runtimes. You should just need to download the Desktop runtime.

https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.8.23.79 See this if this isn't the version you're using

**Comment by MagmaBro123** [comment]
> If you actually read the popup, it says you are missing frameworks for .NET not that you are missing Microsoft.Net runtime.
> 
> Don't follow the above instructions because they're actually out-dated now as the latest pre-release should remove all requirement of needing ASP.Net runtimes. You should just need to download the Desktop runtime.
> 
> https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.8.23.79 See this if this isn't the version you're using

Same issue.

![image](https://user-images.githubusercontent.com/51277766/186712642-1ec01f68-de7b-457f-817a-b6ae779459d6.png)

**Comment by Rayth** [comment]
The release from the website isn't loading the latest version because the latest is marked as pre-release but is the most stable. The link I provided is the one you SHOULD be using.

If you still get an error on that, go to https://dotnet.microsoft.com/en-us/download/dotnet/6.0 and download .NET Desktop Runtime 6.0.8

**Comment by MagmaBro123** [comment]
Fixed apparently. What happened to the 'Switch to Java Launcher' button?

**Comment by Rayth** [comment]
It got removed as an unnecessary feature. Plus the java launcher now is just the standard launcher which also launches bedrock, it just doesn't version switch

**Comment by MagmaBro123** [comment]
Ah.
