### ISSUE TITLE
Totally broken

### ISSUE THREAD

**Issue by TheDood1092** [BedrockLauncher/BedrockLauncher#290]
Downloaded latest release, opted into the xbox insider thing and installed .net. Installer keeps throwing up errors that certain files are in use by another program when there is nothing open, insider login does not work at all even after reinstalling launcher and it won't launch any version of minecraft at all. It also refuses to uninstall and has nuked my minecraft install all together.

**Comment by Rayth** [comment]
I'm going to assume that you're on the old Launcher version and not the new Lite version since you no longer need an insider account due to Minecraft Beta being replaced by Preview. Please download from: https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.8.23.79
MAKE SURE TO READ ALL THE NOTES ON THAT PAGE!

As for uninstalling the one you have now, you can manually delete all the files from where you installed it to. The uninstaller has known issues and is the reason the new versions no longer use an installer or uninstaller and are instead completely portable.

If you have any issues on the version I linked above, open a new Issue and include the Log file which will be located in the "Data/Logs" folder inside where you save the download.
