### ISSUE TITLE
✨ Add authentication support for `OAuth2 Code Flow`

### ISSUE THREAD

**Issue by Rikj000** [BedrockLauncher/BedrockLauncher#315]
## Issue Description
Currently privacy conscious users who legally obtained the game,   
are unable to use the `BedrockLauncher` when either of following is true:
- Windows is used with a [Local Account](https://www.windowscentral.com/how-set-windows-11-without-microsoft-account)
- Windows has been [Ameliorated](https://ameliorated.info/)

## Feature Request
Implementation of the Microsoft [OAuth2 Code Flow](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) for authentication.   
Which would allow Local Windows Accounts to login on the `BedrockLauncher` with their Microsoft Account through:   
https://www.microsoft.com/link

The [MultiMC Launcher](https://github.com/MultiMC/Launcher)'s implementation of this can perhaps be used as an example.

**Comment by Rayth** [comment]
After spending some time looking at this it won't actually be implemented because the launcher doesn't require authentication itself.
Yes, the launcher asks for an account on first launch, but this selected account was only ever used when installing a BETA version of the game. With the release of Preview this is now defunct. Therefore, once we get round to it, this whole selecting account and having beta options in the launcher will be fully removed. The not people mentioned being unable to use the launcher above is more to do with the microsoft store than it is with us.
