### ISSUE TITLE
Launcher wont uninstall

### ISSUE THREAD

**Issue by fueafhweaipo** [BedrockLauncher/BedrockLauncher#366]
I downloaded the old edition of the launcher, and it wont uninstall. I tried deleting the files, but minecraft still opens in 1.13. please help.

**Comment by Rayth** [comment]
We are well aware of the uninstall bug with the old launcher. We don't have a workaround which is why we moved to a portable version. The minecraft issue isn't due to us, you can use the updated launcher to install a later verison, or uninstall minecraft from settings > apps and then install it normally
