### ISSUE TITLE
Add a way to run without administrator 

### ISSUE THREAD

**Issue by CortlandNation9** [BedrockLauncher/BedrockLauncher#412]
I understand administrator rights are necessary for installing the program but why does it need administrator rights to run. I want to install the app for a user that I don't want to give administrator privileges.

**Comment by Rayth** [comment]
our app doesn't actually "install".  The administrator priveliges are required when running because when switching installations or profiles it uses symbolic links to switch between save data which require admin. You could always just run minecraft from the start menu on the other users account after installing from the launcher.
