### ISSUE TITLE
Launcher crashes when clicked on the "..." button on the "new download" part

### ISSUE THREAD

**Issue by DarkAngelMVP** [BedrockLauncher/BedrockLauncher#540]
i was trying to download a beta version but i could not find it, i just clicked the ... button and the launcher crashed.

i dont know why it happened.

My PC specs:

Windows 10
NVIDIA GeForce GT 740
Intel(R) Core(TM) i7 CPU 870 @ 2.93GHz
16 GB Ram

**Comment by DLazaridisGM** [comment]
1) betas can't be accessed sense microsoft/mojang removed the links for the packages 

2) the crash must be because you are using an older version of the launcher 
*The latest version would be (2024.9.7.32)

3) if you have the latest version of the launcher then please join the discord from the bedrock launchers website provided below and open a ticket
https://bedrocklauncher.github.io/

Note: Remember make a backup of your worlds before making any changes
