### ISSUE TITLE
Question| What is the oldest version I can play with the launcher?

### ISSUE THREAD

**Issue by Paco8478** [BedrockLauncher/BedrockLauncher#541]
Does it have the betas and alphas?

**Comment by Rayth** [comment]
The earliest version you can access is 0.14.0.1

You could easily check the version list with the launcher open. Old betas (the ones that were actual beta before beta got changed to preview, not the really old versions) were removed due to them being unavailable for download from the MS store. Previews routinely get removed as well for the same reason. Any further questions, please join the discord as we don't offer support via github anymore.
