### ISSUE TITLE
How do I grant access to the com.mojang folder?

### ISSUE THREAD

**Issue by alexpro756** [BedrockLauncher/BedrockLauncher#79]
When launching the version, I get an error

LOG:
```
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
```
Error code: -2146232800
![Screenshot27-09-2021](https://user-images.githubusercontent.com/88826598/134901811-012f1113-1ae4-42fc-9b66-cfc5e7b74fd3.png)

**Comment by Rayth** [comment]
He translated the error in his title. Looks like the launcher wasn't run in admin mode.

**Comment by TresAbhi** [comment]
@Rayth Yeah, the launcher was **probably not run with UAC**. However, the log needs to explain the error a bit further, and also, the launcher by default prompts UAC anyways, so I don't know what's going on there on his machine.

**Comment by Rayth** [comment]
@TresAbhi he can't help if the log doesn't provide more. He screenshot the error, which granted not being in english doesn't help, but I don't feel that's a reason to mark an issue as invalid, especially without actually giving the OP a chance to reply in the first place. That makes it seem like developers don't care. If you were to add it now, that's a different story as it's been well over 24hours since the original posting and reply and hasn't replied.

**Comment by TresAbhi** [comment]
Here is my workflow for issues like these: I mark them invalid so that the dev doesn't pay attention to it (to save time, because there's no info there anyways), then I wait until either too much time has passed away and the OP hasn't responded, or the problem with the issue gets resolved. Then I do the ritual of marking the version and type of bug.

@Rayth, honestly, you should be allowed to manage issues too. You seem to know how these things work, plus, I can't do this forever \:\)

**Comment by NT690** [comment]
btw the error says "Access denied along the path "C: \ Users \ User \ AppData \ LocalPackages MicrosoftlinecraftUWP_8wekyb3d8bbwe \ LocalState \ games.com.mojang"." So there you go. I used google lens

**Comment by Rayth** [comment]
Closing this as no response from OP
