### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by FireBlaze722** [BedrockLauncher/BedrockLauncher#87]
When I try to open the launcher I get an error.
![IMG_20211020_132722](https://user-images.githubusercontent.com/92849725/138051960-280dfab4-56da-4ddb-979c-e3648a7aeb7e.jpg)

**Comment by TresAbhi** [comment]
@FireBlaze722 
Here's the log you have provided me:
```
Application Starting...
Checking for updates
Check for updates failed
Error:Configuration system failed to initialize
System.Windows.Threading.DispatcherUnhandledExceptionEventArgs
```

I don't see how this is related to the one mentioned in the issue. Since you mentioned that you updated the launcher, it means that an older version was giving you the error, the current version is not to be blamed.

Also, I looked at the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.windows.threading.dispatcherunhandledexceptioneventargs), and seems like it's the [dispatcher](https://docs.microsoft.com/en-us/dotnet/api/system.windows.threading.dispatcher)'s fault, not the launcher's (I may be wrong on this one, @CarJem, any conformation?).

I'm keeping this as invalid until @CarJem gives this issue a direction.

**Comment by FireBlaze722** [comment]
Deleted all the launcher directories, re-installed minecraft, and re-installed the launcher. It works perfectly now, Thank You!
